### ISSUE TITLE
Cannot parse login page!

### ISSUE THREAD

**Issue by Hansukie** [HitomaruKonpaku/SadPanda#8]
When trying to log in, it returns that error message. 

Could this be due to a new chrome update?

**Comment by HitomaruKonpaku** [comment]
Do you have any image of it?

**Comment by Hansukie** [comment]
> Do you have any image of it?

Here's a screen pic:

https://i.ibb.co/VjxjDnS/Error.png

**Comment by HitomaruKonpaku** [comment]
Can you update the extension then click and open those url in chrome extensions

![image](https://user-images.githubusercontent.com/9608105/54474362-63a8d480-4816-11e9-81df-f086573db6bb.png)

Then tell me what is the response

![image](https://user-images.githubusercontent.com/9608105/54474395-acf92400-4816-11e9-83bc-7d758f85d8d5.png)

**Comment by Hansukie** [comment]
> Can you update the extension then click and open those url in chrome extensions 
> Then tell me what is the response

I still get the same "Error parsing login result page!" error. I checked the inspect views and for some reason, it's empty.

Here's a pic:

https://i.ibb.co/p39g28Z/error2.png

I have opened a fresh incognito window after closing all the old incognito windows and tried logging in, same error. 

Also tried it in a normal window (not incognito) and still get the error. 

I can log into e-hentai.org perfectly fine.

**Comment by Hansukie** [comment]
> > Can you update the extension then click and open those url in chrome extensions
> > Then tell me what is the response

I still get the same "Error parsing login result page!" error. I checked the inspect views and for some reason, it's empty.
> 
> Here;s a pic:
> 
> https://i.ibb.co/p39g28Z/error2.png
> 
> I have opened a fresh incognito window after closing all the old incognito windows and tried logging in, same error.
> 
> Also tried it in a normal window (not incognito) and still get the error.

**Comment by HitomaruKonpaku** [comment]
@Hansukie ehhh im sorry but not sure why tbh...

**Comment by tofuBox** [comment]
Seems to be due to this issue:

![CORB-Error](https://user-images.githubusercontent.com/40531521/54485594-a8dd0d00-48cf-11e9-86bc-3af77404dd91.jpg)

**Comment by HitomaruKonpaku** [comment]
@tofuBox thanks, i will check that

**Comment by HitomaruKonpaku** [comment]
I pushed temporary fix for this issue.

New chrome 73 not allow to read the response so... ¯\_(ツ)_/¯

c69aa701accbc8a211f952576f9ffaa8e1bba4e2

**Comment by tofuBox** [comment]
> I pushed temporary fix for this issue.
> 
> New chrome 73 not allow to read the response so... ¯_(ツ)_/¯
> 
> [c69aa70](https://github.com/HitomaruKonpaku/SadPanda/commit/c69aa701accbc8a211f952576f9ffaa8e1bba4e2)

Yup, that seems to fix it. Though it throws that error message briefly, but is still able to log in properly.
Chrome recently pushed a major security update, so that might be the cause of it.

**Comment by Hansukie** [comment]
@HitomaruKonpaku Thanks a lot! It's working now, even though it still show the error, it logs in properly now. 

@tofubox Thanks for locating the problem!

**Comment by HitomaruKonpaku** [comment]
@Hansukie will try to fix it when i read some more about chrome update

Thanks

**Comment by HitomaruKonpaku** [comment]
Pushed the new code 2352132de41730b348d7325d1682eecac4504a0b

Can you guys check if it work?

**Comment by tofuBox** [comment]
> Pushed the new code [2352132](https://github.com/HitomaruKonpaku/SadPanda/commit/2352132de41730b348d7325d1682eecac4504a0b)
> 
> Can you guys check if it work?

Yup, it's working properly now. Thanks for maintaining it.

**Comment by HitomaruKonpaku** [comment]
Your welcome

Benefit me, too :D
